/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SlotsRouteImport } from './routes/slots'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as My42RouteImport } from './routes/my42'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as ProfileLoginRouteImport } from './routes/profile.$login'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotsRoute = SlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const My42Route = My42RouteImport.update({
  id: '/my42',
  path: '/my42',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileLoginRoute = ProfileLoginRouteImport.update({
  id: '/profile/$login',
  path: '/profile/$login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/events': typeof EventsRoute
  '/locations': typeof LocationsRoute
  '/my42': typeof My42Route
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/slots': typeof SlotsRoute
  '/students': typeof StudentsRoute
  '/profile/$login': typeof ProfileLoginRoute
  '/project/$id': typeof ProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/events': typeof EventsRoute
  '/locations': typeof LocationsRoute
  '/my42': typeof My42Route
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/slots': typeof SlotsRoute
  '/students': typeof StudentsRoute
  '/profile/$login': typeof ProfileLoginRoute
  '/project/$id': typeof ProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/events': typeof EventsRoute
  '/locations': typeof LocationsRoute
  '/my42': typeof My42Route
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/slots': typeof SlotsRoute
  '/students': typeof StudentsRoute
  '/profile/$login': typeof ProfileLoginRoute
  '/project/$id': typeof ProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-error'
    | '/dashboard'
    | '/evaluations'
    | '/events'
    | '/locations'
    | '/my42'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/slots'
    | '/students'
    | '/profile/$login'
    | '/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-error'
    | '/dashboard'
    | '/evaluations'
    | '/events'
    | '/locations'
    | '/my42'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/slots'
    | '/students'
    | '/profile/$login'
    | '/project/$id'
  id:
    | '__root__'
    | '/'
    | '/auth-error'
    | '/dashboard'
    | '/evaluations'
    | '/events'
    | '/locations'
    | '/my42'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/slots'
    | '/students'
    | '/profile/$login'
    | '/project/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthErrorRoute: typeof AuthErrorRoute
  DashboardRoute: typeof DashboardRoute
  EvaluationsRoute: typeof EvaluationsRoute
  EventsRoute: typeof EventsRoute
  LocationsRoute: typeof LocationsRoute
  My42Route: typeof My42Route
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SlotsRoute: typeof SlotsRoute
  StudentsRoute: typeof StudentsRoute
  ProfileLoginRoute: typeof ProfileLoginRoute
  ProjectIdRoute: typeof ProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slots': {
      id: '/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof SlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my42': {
      id: '/my42'
      path: '/my42'
      fullPath: '/my42'
      preLoaderRoute: typeof My42RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$login': {
      id: '/profile/$login'
      path: '/profile/$login'
      fullPath: '/profile/$login'
      preLoaderRoute: typeof ProfileLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthErrorRoute: AuthErrorRoute,
  DashboardRoute: DashboardRoute,
  EvaluationsRoute: EvaluationsRoute,
  EventsRoute: EventsRoute,
  LocationsRoute: LocationsRoute,
  My42Route: My42Route,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SlotsRoute: SlotsRoute,
  StudentsRoute: StudentsRoute,
  ProfileLoginRoute: ProfileLoginRoute,
  ProjectIdRoute: ProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
