/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SlotsRouteImport } from './routes/slots'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileLoginRouteImport } from './routes/profile.$login'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotsRoute = SlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileLoginRoute = ProfileLoginRouteImport.update({
  id: '/profile/$login',
  path: '/profile/$login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/evaluations': typeof EvaluationsRoute
  '/events': typeof EventsRoute
  '/locations': typeof LocationsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/slots': typeof SlotsRoute
  '/students': typeof StudentsRoute
  '/profile/$login': typeof ProfileLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/evaluations': typeof EvaluationsRoute
  '/events': typeof EventsRoute
  '/locations': typeof LocationsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/slots': typeof SlotsRoute
  '/students': typeof StudentsRoute
  '/profile/$login': typeof ProfileLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/evaluations': typeof EvaluationsRoute
  '/events': typeof EventsRoute
  '/locations': typeof LocationsRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/slots': typeof SlotsRoute
  '/students': typeof StudentsRoute
  '/profile/$login': typeof ProfileLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-error'
    | '/evaluations'
    | '/events'
    | '/locations'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/slots'
    | '/students'
    | '/profile/$login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-error'
    | '/evaluations'
    | '/events'
    | '/locations'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/slots'
    | '/students'
    | '/profile/$login'
  id:
    | '__root__'
    | '/'
    | '/auth-error'
    | '/evaluations'
    | '/events'
    | '/locations'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/slots'
    | '/students'
    | '/profile/$login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthErrorRoute: typeof AuthErrorRoute
  EvaluationsRoute: typeof EvaluationsRoute
  EventsRoute: typeof EventsRoute
  LocationsRoute: typeof LocationsRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SlotsRoute: typeof SlotsRoute
  StudentsRoute: typeof StudentsRoute
  ProfileLoginRoute: typeof ProfileLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slots': {
      id: '/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof SlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$login': {
      id: '/profile/$login'
      path: '/profile/$login'
      fullPath: '/profile/$login'
      preLoaderRoute: typeof ProfileLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthErrorRoute: AuthErrorRoute,
  EvaluationsRoute: EvaluationsRoute,
  EventsRoute: EventsRoute,
  LocationsRoute: LocationsRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SlotsRoute: SlotsRoute,
  StudentsRoute: StudentsRoute,
  ProfileLoginRoute: ProfileLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
